
package pl.training.bank.client.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Bank", targetNamespace = "http://api.bank.training.pl/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Bank {


    /**
     * 
     * @param arg0
     * @return
     *     returns pl.training.bank.client.soap.AccountDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://api.bank.training.pl/", className = "pl.training.bank.client.soap.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://api.bank.training.pl/", className = "pl.training.bank.client.soap.GetAccountResponse")
    public AccountDto getAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns pl.training.bank.client.soap.AccountDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://api.bank.training.pl/", className = "pl.training.bank.client.soap.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://api.bank.training.pl/", className = "pl.training.bank.client.soap.CreateAccountResponse")
    public AccountDto createAccount();

}
